 TrajectoryPlannerROS:
   max_vel_x: 0.5
   min_vel_x: -0.5
   max_vel_theta: 4.25
   min_vel_theta: 2.5
   min_in_place_vel_theta: 2.5
   acc_lim_theta: 0.2
   acc_lim_x: 0.1
   acc_lim_y: 0.1
   holonomic_robot: false
   controller_frequency: 20.0
   meter_scoring: true

