DWAPlannerROS: 
   acc_lim_th: 6.4 #3.2
   acc_lim_x: 2.5 
   acc_lim_y: 2.5 

   max_vel_x: 0.5 #0.55
   min_vel_x: 0.0 #0.0

   max_vel_y: 0.0
   min_vel_y: 0.0 

   max_vel_trans: 0.5 #0.55
   min_vel_trans: 0.1 #0.1

   max_vel_theta: 4.25 #1.0 #4.25
   min_vel_theta: 2.5 #0.4 #2.5

   sim_time: 1.7 
   sim_granularity: 0.025 

   goal_distance_bias: 24.0 
   path_distance_bias: 64.0 #32 

   occdist_scale: 0.01 
   stop_time_buffer: 0.2 
   oscillation_reset_dist: 0.05 
   forward_point_distance: 0.325 
   scaling_speed: 0.25 
   max_scaling_factor: 0.2 

   vx_samples: 3 
   vy_samples: 10 

   vtheta_samples: 20 
   sim_period: 0.1 

   xy_goal_tolerance: 0.2 
   yaw_goal_tolerance: 0.17 

   theta_stopped_vel: 0.01 
   trans_stopped_vel: 0.01

   orientation_mode: 1
